version: "3"

services:
  mySqlDB:
    image: mysql
    restart: always
    container_name: nodemysql
    environment:
      - MYSQL_ROOT_PASSWORD=TestDB@home2
    volumes:
      - ./mySqlDB:/var/lib/mysql
    ports:
      - "3306:3306"
  myPostgresDB:
    image: postgres
    restart: always
    container_name: nodepostgres
    environment:
      - MPOSTGRES_PASSWORD=TestDB@home2
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
