version: "3"

services:
  mySqlDB:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: nodemysql
    environment:
      - MYSQL_ROOT_PASSWORD=TestDB@home2
    volumes:
      - ./mySqlDB:/var/lib/mysql
    ports:
      - "3306:3306"
  myMariaDB:
    image: mariadb
    restart: always
    container_name: nodemariadb
    environment:
      - MYSQL_ROOT_PASSWORD=TestDB@home2
    volumes:
      - ./MariaDB:/var/lib/mysql
    ports:
      - "3307:3306"
  myPostgresDB:
    image: postgres
    restart: always
    container_name: nodepostgres
    environment:
      - POSTGRES_PASSWORD=TestDB@home2
    volumes:
      - ./postgresDB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mynodeapp:
    build: ./nodeApp
    depends_on:
      - mySqlDB
      - myPostgresDB
      - myMariaDB
    container_name: mynodemultidb
    command: nodemon -L
    volumes:
      - ./nodeApp:/code
    ports:
      - "8000:8000"
      - "5858:5858"
      - "3000:3000"
    expose:
      - "3000"
  mynodeapptwo:
    image: nodewithmultidb_mynodeapp
    depends_on:
      - mySqlDB
      - myPostgresDB
      - myMariaDB
      - mynodeapp
    container_name: mynodemultidbtwo
    command: nodemon -L
    volumes:
      - ./nodeApp:/code
    ports:
      - "8001:8000"
      - "5859:5858"
      - "3001:3000"
    expose:
      - "3000"
  mynginx:
    image: nginx
    depends_on:
      - mySqlDB
      - myPostgresDB
      - myMariaDB
      - mynodeapp
      - mynodeapptwo
    container_name: mynginxmultidb
    volumes:
      - ./nginx/nginxconfig:/etc/nginx/
    ports:
      - "5000:80"
